In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import calendar

In [3]:
customers={
    'customer_id':np.arange(1,201),
    'age':np.random.randint(18, 40, 200),
    'gender':np.random.choice(['Male', 'Female'], 200),
    'city':np.random.choice(['Mumbai', 'Pune', 'Lucknow', 'Jaipur', 'Surat', 'Bhopal', 'Indore'], 200),
}
months=list(calendar.month_name)[1:]
df1=pd.DataFrame(customers)

In [4]:
orders={
    'order_id':np.arange(1, 1001),
    'customer_id':np.random.choice(customers['customer_id'], 1000),
    'prod_category':np.random.choice(['elec', 'toy', 'beauty'], 1000),
    'quantity':np.random.randint(1,10, 1000),
    'price':np.random.randint(699, 2999, 1000),
    'order_month':np.random.choice(months, 1000)
}
df2=pd.DataFrame(orders)

In [5]:
products={
    'prod_category':['elec', 'toy', 'beauty'],
    'profit_margin':[0.25, 0.40, 0.5]
}
df3=pd.DataFrame(products)

In [6]:
df4=pd.merge(df1, df2)

In [9]:
dff=pd.merge(df3, df4)

In [14]:
dff['revenue']=dff['quantity']*dff['price']
dff

,prod_category,profit_margin,customer_id,age,gender,city,order_id,quantity,price,order_month,revenue
0,elec,0.25,1,28,Male,Mumbai,78,4,2166,May,8664
1,elec,0.25,2,20,Male,Mumbai,798,2,2753,September,5506
2,elec,0.25,3,27,Male,Pune,781,1,1401,February,1401
3,elec,0.25,4,19,Female,Mumbai,535,6,2578,November,15468
4,elec,0.25,4,19,Female,Mumbai,682,5,2799,January,13995
...,...,...,...,...,...,...,...,...,...,...,...
995,beauty,0.50,197,23,Male,Pune,79,8,1847,November,14776
996,beauty,0.50,197,23,Male,Pune,779,2,2390,May,4780
997,beauty,0.50,197,23,Male,Pune,973,9,2497,January,22473
998,beauty,0.50,198,24,Female,Mumbai,354,2,1937,January,3874
999,beauty,0.50,199,18,Female,Surat,390,9,1685,February,15165

In [16]:
revenue_pivot=pd.pivot_table(
        dff,
        values='revenue',
        index='order_month',
        columns='prod_category',
        aggfunc='sum'
    )
revenue_pivot

prod_category  beauty    elec     toy
order_month
April          279575  166946  292100
August         189266  263365  256866
December       220650  223406  283778
February       307058  251911  295478
January        225888  331013  229129
July           287283  196198  285869
June           172395  104373  272083
March          262613  192086  291216
May            239085  242447  223570
November       412858  290934  332332
October        207969  125993  311168
September      190322  307684  386666

In [23]:
a=dff.groupby('city')['revenue'].mean()
pd.pivot_table(
    dff,
    index='city',
    values='revenue',
    aggfunc='mean'
)

             revenue
city
Bhopal   9162.569343
Indore   9535.410405
Jaipur   9085.518519
Lucknow  9392.214953
Mumbai   8209.380282
Pune     8723.982906
Surat    9911.903704